import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/providers/ThemeProvider";
import ConvexClientProvider from "@/components/providers/ConvexProvider";
import { Toaster } from "sonner";
import ModalProvider from "@/components/providers/ModalProvider";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { SpeedInsights } from "@vercel/speed-insights/next"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notion",
  description: "Generated by create next app",
  icons:{
    icon:{
      url:"/logo.svg"
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ConvexClientProvider>
          <EdgeStoreProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              storageKey="notion-theme"
            >
              <Toaster position="bottom-right"/>
              <ModalProvider/>
              {children}
              <SpeedInsights/>
            </ThemeProvider> 
          </EdgeStoreProvider>          
        </ConvexClientProvider>      
        </body>
    </html>
  );
}
